apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2025-04-05T13:01:42Z"
  name: developer
  namespace: default
  resourceVersion: "991"
  uid: be67a880-ca2c-448e-a7ea-a55fd3c37218
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - delete



apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2025-04-05T13:01:42Z"
  name: dev-user-binding
  namespace: default
  resourceVersion: "992"
  uid: 0a5ff1db-5f86-4499-b61d-3fd263442e83
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user
