
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_Host: c3FsMDE=
  DB_Password: cGFzc3dvcmQxMjM=
  DB_User: cm9vdA==

// How to encode in base64

echo "dev" | base64

// decode

echo "encoded-string" | base64 --decode   //or use -d

// In pod yaml, to load all secrets
envFrom:
      - secretRef:
          name: db-secret

env:
  - name: DB_Host
    valueFrom:
      secretKeyRef:
        name: <Secret-name>
        key: <key name from secret>
