apiVersion: v1
kind: Pod
metadata:
  labels:
    app: result
  name: result
spec:
  containers:
  - image: dockersamples/examplevotingapp_result
    name: result
  - image: <another-image-name>
    name: <container-name-of-your-choice>
    volumeMounts:
    - mountPath: /var/log/event-simulator/
      name: log-volume
